In [ ]:
# Kết nối với google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
# Load tập dữ liệu
df = pd.read_csv('/content/drive/MyDrive/Foreign-Direct-Investment/data/fdi_country_partners_vi.csv',index_col='TT').drop('Unnamed: 9', axis=1)

In [ ]:
# In ra 5 dòng đầu tiên
df.head(5)

,Đối tác,Số dự án cấp mới,Vốn đăng ký cấp mới (triệu USD),Số lượt dự án điều chỉnh,Vốn đăng ký điều chỉnh\n(triệu USD),Số lượt góp vốn mua cổ phần,"Giá trị góp vốn, mua cổ phần \n(triệu USD)",Năm
TT,,,,,,,,
1,Hàn Quốc,702,2678.517,260,4048.4,NaN,NaN,2015
2,Malaysia,27,2447.488,15,30.8,NaN,NaN,2015
3,Nhật Bản,299,1284.983,157,556.7,NaN,NaN,2015
4,Đài Loan,110,940.404,61,457.9,NaN,NaN,2015
5,Samoa,24,1314.037,8,80.6,NaN,NaN,2015

In [ ]:
# Thống kê các cột có trong DataFrame
print("Column before modification:")
for x, column in enumerate(df.columns):
    print("Column {}: {}".format(x, column))

print("------------------------------")
print("Modification processing...")
# Loại bỏ khoảng trắng ở đầu và cuối mỗi tên cột
df.columns = df.columns.str.strip()

# Đổi ký tự " \n" thành " "
df.columns = df.columns.str.replace(" \n"," ")

# Đổi ký tự "\n" thành ""
df.columns = df.columns.str.replace("\n"," ")
print("------------------------------")

# Kiểm tra lại các cột có trong DataFrame
print("Column after modification:")
for x, column in enumerate(df.columns):
    print("Column {}: {}".format(x, column))

Column before modification:
Column 0: Đối tác
Column 1:  Số dự án cấp mới
Column 2:  Vốn đăng ký cấp mới (triệu USD)
Column 3:  Số lượt dự án điều chỉnh
Column 4:  Vốn đăng ký điều chỉnh
(triệu USD)
Column 5:  Số lượt góp vốn mua cổ phần
Column 6:  Giá trị góp vốn, mua cổ phần
(triệu USD)
Column 7: Năm
------------------------------
Modification processing...
------------------------------
Column after modification:
Column 0: Đối tác
Column 1: Số dự án cấp mới
Column 2: Vốn đăng ký cấp mới (triệu USD)
Column 3: Số lượt dự án điều chỉnh
Column 4: Vốn đăng ký điều chỉnh (triệu USD)
Column 5: Số lượt góp vốn mua cổ phần
Column 6: Giá trị góp vốn, mua cổ phần (triệu USD)
Column 7: Năm

In [ ]:
# Khởi tạo mảng chứa các cột cần loại bỏ khoảng trắng trong mỗi giá trị
column_to_strip = df.drop('Năm', axis=1).columns

# Khởi tạo vòng lặp duyệt qua các giá trị trong cột và loại bỏ khoảng trắng dư thừa
for column in column_to_strip:
  df[column] = df[column].str.strip()

In [ ]:
# Thống kê số lượng các giá trị thiếu ở mỗi cột
print(df.isnull().sum())
print("-> The total number of initial null values is: {}".format(df.isnull().sum().sum()))

print("------------------------------")
print("Fillna processing...")
# Thay thế số giá trị null thành 0
# Thay thế các chuỗi có dạng " -" và "- " thành ""
df = df.replace('-',0)
df = df.fillna(0)
print("------------------------------")

# Kiểm tra lại số giá trị null
print(df.isnull().sum())
print("-> The total number of null values after substitution is: {}".format(df.isnull().sum().sum()))

Đối tác                                       0
Số dự án cấp mới                            150
Vốn đăng ký cấp mới (triệu USD)             150
Số lượt dự án điều chỉnh                    296
Vốn đăng ký điều chỉnh (triệu USD)          268
Số lượt góp vốn mua cổ phần                 114
Giá trị góp vốn, mua cổ phần (triệu USD)    113
Năm                                           0
dtype: int64
-> The total number of initial null values is: 1091
------------------------------
Fillna processing...
------------------------------
Đối tác                                     0
Số dự án cấp mới                            0
Vốn đăng ký cấp mới (triệu USD)             0
Số lượt dự án điều chỉnh                    0
Vốn đăng ký điều chỉnh (triệu USD)          0
Số lượt góp vốn mua cổ phần                 0
Giá trị góp vốn, mua cổ phần (triệu USD)    0
Năm                                         0
dtype: int64
-> The total number of null values after substitution is: 0

In [ ]:
# Khởi tạo mảng chứa các cột cần chuyển đổi kiểu int
column_to_int = ['Số dự án cấp mới', 'Số lượt dự án điều chỉnh', 'Số lượt góp vốn mua cổ phần']

# Khởi tạo vòng lặp để chuyển đổi các cột sang kiểu int
for column in column_to_int:
  df[column] = df[column].replace(',','', regex=True)
  df[column] = df[column].astype(int)

In [ ]:
# Khởi tạo mảng chứa các cột cần chuyển đổi kiểu float
column_to_float = ['Vốn đăng ký cấp mới (triệu USD)', 'Vốn đăng ký điều chỉnh (triệu USD)', 'Giá trị góp vốn, mua cổ phần (triệu USD)']

# Khởi tạo vòng lặp để chuyển đổi các cột sang kiểu float
for column in column_to_float:

  # Xóa các kí tự đặc biệt
  df[column] = df[column].replace(',','', regex=True)
  df[column] = df[column].replace('\(','',regex=True)
  df[column] = df[column].replace('\)','',regex=True)

  # Chuyển đổi sang kiểu float
  df[column] = df[column].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 834 entries, 1 to 834
Data columns (total 8 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Đối tác                                   834 non-null    object
 1   Số dự án cấp mới                          834 non-null    int64
 2   Vốn đăng ký cấp mới (triệu USD)           834 non-null    float64
 3   Số lượt dự án điều chỉnh                  834 non-null    int64
 4   Vốn đăng ký điều chỉnh (triệu USD)        834 non-null    float64
 5   Số lượt góp vốn mua cổ phần               834 non-null    int64
 6   Giá trị góp vốn, mua cổ phần (triệu USD)  834 non-null    float64
 7   Năm                                       834 non-null    int64
dtypes: float64(3), int64(4), object(1)
memory usage: 58.6+ KB

In [ ]:
df.head()

,Đối tác,Số dự án cấp mới,Vốn đăng ký cấp mới (triệu USD),Số lượt dự án điều chỉnh,Vốn đăng ký điều chỉnh (triệu USD),Số lượt góp vốn mua cổ phần,"Giá trị góp vốn, mua cổ phần (triệu USD)",Năm
TT,,,,,,,,
1,Hàn Quốc,702,2678.517,260,4048.4,0,0.0,2015
2,Malaysia,27,2447.488,15,30.8,0,0.0,2015
3,Nhật Bản,299,1284.983,157,556.7,0,0.0,2015
4,Đài Loan,110,940.404,61,457.9,0,0.0,2015
5,Samoa,24,1314.037,8,80.6,0,0.0,2015

In [ ]:
df.to_csv('/content/drive/MyDrive/Foreign-Direct-Investment/data/fdi_country_partners_vi_clean.csv')

In [ ]:
df_clean = pd.read_csv('/content/drive/MyDrive/Foreign-Direct-Investment/data/fdi_country_partners_vi_clean.csv')

df_clean.head()

,TT,Đối tác,Số dự án cấp mới,Vốn đăng ký cấp mới (triệu USD),Số lượt dự án điều chỉnh,Vốn đăng ký điều chỉnh (triệu USD),Số lượt góp vốn mua cổ phần,"Giá trị góp vốn, mua cổ phần (triệu USD)",Năm
0,1,Hàn Quốc,702,2678.517,260,4048.4,0,0.0,2015
1,2,Malaysia,27,2447.488,15,30.8,0,0.0,2015
2,3,Nhật Bản,299,1284.983,157,556.7,0,0.0,2015
3,4,Đài Loan,110,940.404,61,457.9,0,0.0,2015
4,5,Samoa,24,1314.037,8,80.6,0,0.0,2015